import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../navbarr/Navbar";
import { IoLogoAngular } from "react-icons/io";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Abduulah(A)-Cars",
  description: "Generated by create next app",
  icons:{
    icon:"./letter-a.png"
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
